/*###################################################################
### This JavaFX document was generated by Inkscape
### http://www.inkscape.org
### Created: Mon Jun 11 23:49:07 2018
### Version: 0.92.2 (5c3e80d, 2017-08-06)
#####################################################################
### NOTES:
### ============
### JavaFX information can be found at
### http://www.javafx.com/
###
### If you have any problems with this output, please see the
### Inkscape project at http://www.inkscape.org, or visit
### the #inkscape channel on irc.freenode.net . 
###
###################################################################*/


/*###################################################################
##   Exports in this file
##==========================
##    Shapes   : 3
##    Nodes    : 25
###################################################################*/


import javafx.scene.*;
import javafx.scene.shape.*;
import javafx.scene.transform.*;
import javafx.scene.paint.*;



public class test6-connected extends CustomNode {
    /** path path13 */
    function path13() : Path {
        Path {
            id: "path13"
            opacity: 1.00000000
            fill: Color.rgb(0xff, 0x00, 0x00, 1.00000000)
            stroke: Color.rgb(0x00, 0x00, 0x00, 1.00000000)
            strokeWidth: 0.26458332
            strokeLineCap: StrokeLineCap.BUTT
            strokeLineJoin: StrokeLineJoin.MITER
            strokeMiterLimit: 4.00000000
            elements: [
                MoveTo {
                    x: 635.58720409
                    y: -380.00000475
                },
                LineTo {
                    x: 431.32105535
                    y: -368.66103839
                },
                LineTo {
                    x: 148.23401181
                    y: -570.41584234
                },
                LineTo {
                    x: 177.54274587
                    y: -706.44613494
                },
                LineTo {
                    x: 478.74358322
                    y: -588.76267531
                },
                LineTo {
                    x: 635.58720409
                    y: -380.00000475
                },
                ClosePath {},
            ] // elements
        }; // Path
    } // end path path13

    /** path path15 */
    function path15() : Path {
        Path {
            id: "path15"
            opacity: 1.00000000
            fill: Color.rgb(0xff, 0x00, 0x00, 1.00000000)
            stroke: Color.rgb(0x00, 0x00, 0x00, 1.00000000)
            strokeWidth: 0.26458332
            strokeLineCap: StrokeLineCap.BUTT
            strokeLineJoin: StrokeLineJoin.MITER
            strokeMiterLimit: 4.00000000
            elements: [
                MoveTo {
                    x: 292.85715105
                    y: -917.14283157
                },
                LineTo {
                    x: 199.30310786
                    y: -839.80531109
                },
                LineTo {
                    x: 96.84096582
                    y: -904.88188535
                },
                LineTo {
                    x: 127.06992266
                    y: -1022.43894060
                },
                LineTo {
                    x: 248.21458748
                    y: -1030.01662210
                },
                LineTo {
                    x: 292.85715105
                    y: -917.14283157
                },
                ClosePath {},
            ] // elements
        }; // Path
    } // end path path15

    /** path path3709 */
    function path3709() : Path {
        Path {
            id: "path3709"
            opacity: 1.00000000
            stroke: Color.rgb(0x00, 0x00, 0x00, 1.00000000)
            strokeWidth: 0.26458332
            strokeLineCap: StrokeLineCap.BUTT
            strokeLineJoin: StrokeLineJoin.MITER
            strokeMiterLimit: 4.00000000
            elements: [
                MoveTo {
                    x: 229.59583370
                    y: -864.84713953
                },
                LineTo {
                    x: 339.54174992
                    y: -643.15082835
                },
                LineTo {
                    x: 229.59583370
                    y: -864.84713953
                },
            ] // elements
        }; // Path
    } // end path path3709

   override function create(): Node {
       Group {
           content: [
               path13(),
               path15(),
               path3709(),
           ] // content
           transforms: Translate { x : -71.84096582, y : 1055.01662210 }
       } // Group
   } // function create()
} // class test6-connected


/*###################################################################
### E N D   C L A S S    test6-connected
###################################################################*/


