/*###################################################################
### This PovRay document was generated by Inkscape
### http://www.inkscape.org
### Created: Mon Jun 11 23:47:26 2018
### Version: 0.92.2 (5c3e80d, 2017-08-06)
#####################################################################
### NOTES:
### ============
### POVRay information can be found at
### http://www.povray.org
###
### The 'AllShapes' objects at the bottom are provided as a
### preview of how the output would look in a trace.  However,
### the main intent of this file is to provide the individual
### shapes for inclusion in a POV project.
###
### For an example of how to use this file, look at
### share/examples/istest.pov
###
### If you have any problems with this output, please see the
### Inkscape project at http://www.inkscape.org, or visit
### the #inkscape channel on irc.freenode.net . 
###
###################################################################*/


/*###################################################################
##   Exports in this file
##==========================
##    Shapes   : 3
##    Segments : 12
##    Nodes    : 96
###################################################################*/



/*###################################################
### PRISM:  path13
###################################################*/
#declare path13 = prism {
    linear_sweep
    bezier_spline
    1.0, //top
    0.0, //bottom
    20 //nr points
    /*   0*/ <635.58720409, 380.00000475>, <635.58720409, 380.00000475>, <431.32105535, 368.66103839>, <431.32105535, 368.66103839>,
    /*   1*/ <431.32105535, 368.66103839>, <431.32105535, 368.66103839>, <148.23401181, 570.41584234>, <148.23401181, 570.41584234>,
    /*   2*/ <148.23401181, 570.41584234>, <148.23401181, 570.41584234>, <177.54274587, 706.44613494>, <177.54274587, 706.44613494>,
    /*   3*/ <177.54274587, 706.44613494>, <177.54274587, 706.44613494>, <478.74358322, 588.76267531>, <478.74358322, 588.76267531>,
    /*   4*/ <478.74358322, 588.76267531>, <478.74358322, 588.76267531>, <635.58720409, 380.00000475>, <635.58720409, 380.00000475>
}
#declare path13_MIN_X    = 148.23401181;
#declare path13_CENTER_X = 391.91060795;
#declare path13_MAX_X    = 635.58720409;
#declare path13_WIDTH    = 487.35319229;
#declare path13_MIN_Y    = 368.66103839;
#declare path13_CENTER_Y = 537.55358666;
#declare path13_MAX_Y    = 706.44613494;
#declare path13_HEIGHT   = 337.78509655;
#declare path13_COLOR    = rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000>;
/*###################################################
### end path13
###################################################*/



/*###################################################
### PRISM:  path15
###################################################*/
#declare path15 = prism {
    linear_sweep
    bezier_spline
    1.0, //top
    0.0, //bottom
    20 //nr points
    /*   0*/ <292.85715105, 917.14283157>, <292.85715105, 917.14283157>, <199.30310786, 839.80531109>, <199.30310786, 839.80531109>,
    /*   1*/ <199.30310786, 839.80531109>, <199.30310786, 839.80531109>, <96.84096582, 904.88188535>, <96.84096582, 904.88188535>,
    /*   2*/ <96.84096582, 904.88188535>, <96.84096582, 904.88188535>, <127.06992266, 1022.43894060>, <127.06992266, 1022.43894060>,
    /*   3*/ <127.06992266, 1022.43894060>, <127.06992266, 1022.43894060>, <248.21458748, 1030.01662210>, <248.21458748, 1030.01662210>,
    /*   4*/ <248.21458748, 1030.01662210>, <248.21458748, 1030.01662210>, <292.85715105, 917.14283157>, <292.85715105, 917.14283157>
}
#declare path15_MIN_X    = 96.84096582;
#declare path15_CENTER_X = 194.84905844;
#declare path15_MAX_X    = 292.85715105;
#declare path15_WIDTH    = 196.01618523;
#declare path15_MIN_Y    = 839.80531109;
#declare path15_CENTER_Y = 934.91096659;
#declare path15_MAX_Y    = 1030.01662210;
#declare path15_HEIGHT   = 190.21131101;
#declare path15_COLOR    = rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000>;
/*###################################################
### end path15
###################################################*/



/*###################################################
### PRISM:  path3709
###################################################*/
#declare path3709 = prism {
    linear_sweep
    bezier_spline
    1.0, //top
    0.0, //bottom
    8 //nr points
    /*   0*/ <229.59583370, 864.84713953>, <229.59583370, 864.84713953>, <339.54174992, 643.15082835>, <339.54174992, 643.15082835>,
    /*   1*/ <339.54174992, 643.15082835>, <339.54174992, 643.15082835>, <229.59583370, 864.84713953>, <229.59583370, 864.84713953>
}
#declare path3709_MIN_X    = 229.59583370;
#declare path3709_CENTER_X = 284.56879181;
#declare path3709_MAX_X    = 339.54174992;
#declare path3709_WIDTH    = 109.94591622;
#declare path3709_MIN_Y    = 643.15082835;
#declare path3709_CENTER_Y = 753.99898394;
#declare path3709_MAX_Y    = 864.84713953;
#declare path3709_HEIGHT   = 221.69631118;
/*###################################################
### end path3709
###################################################*/



/*###################################################
### UNION OF ALL SHAPES IN DOCUMENT
###################################################*/


/**
 * Allow the user to redefine the finish{}
 * by declaring it before #including this file
 */
#ifndef (AllShapes_Finish)
#declare AllShapes_Finish = finish {
    phong 0.5
    reflection 0.3
    specular 0.5
}
#end


#declare AllShapes = union {
    object { path13
        texture { 
            pigment { rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000> }
            finish { AllShapes_Finish }
            } 
        } 
    object { path15
        texture { 
            pigment { rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000> }
            finish { AllShapes_Finish }
            } 
        } 
    object { path3709
        texture { 
            pigment { rgb <0,0,0> }
            finish { AllShapes_Finish }
            } 
        } 
}



/*#### Same union, but with Z-diffs (actually Y in pov) ####*/


/**
 * Allow the user to redefine the Z-Increment
 */
#ifndef (AllShapes_Z_Increment)
#declare AllShapes_Z_Increment = 0.06666667;
#end

#declare AllShapes_Z_Scale = 1.0;


#declare AllShapes_Z = union {
    object { path13
        texture { 
            pigment { rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000> }
            finish { AllShapes_Finish }
            } 
        scale <1, AllShapes_Z_Scale, 1>
        } 
#declare AllShapes_Z_Scale = AllShapes_Z_Scale + AllShapes_Z_Increment;

    object { path15
        texture { 
            pigment { rgbf <1.00000000, 0.00000000, 0.00000000, 0.00000000> }
            finish { AllShapes_Finish }
            } 
        scale <1, AllShapes_Z_Scale, 1>
        } 
#declare AllShapes_Z_Scale = AllShapes_Z_Scale + AllShapes_Z_Increment;

    object { path3709
        texture { 
            pigment { rgb <0,0,0> }
            finish { AllShapes_Finish }
            } 
        scale <1, AllShapes_Z_Scale, 1>
        } 
#declare AllShapes_Z_Scale = AllShapes_Z_Scale + AllShapes_Z_Increment;

}
#declare AllShapes_MIN_X    = 96.84096582;
#declare AllShapes_CENTER_X = 366.21408496;
#declare AllShapes_MAX_X    = 635.58720409;
#declare AllShapes_WIDTH    = 538.74623827;
#declare AllShapes_MIN_Y    = 368.66103839;
#declare AllShapes_CENTER_Y = 699.33883024;
#declare AllShapes_MAX_Y    = 1030.01662210;
#declare AllShapes_HEIGHT   = 661.35558371;
/*##############################################
### end AllShapes
##############################################*/




/*###################################################################
### E N D    F I L E
###################################################################*/


